import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { prisma } from "@/lib/prisma";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export async function generateMetadata(): Promise<Metadata> {
  const profile = await prisma.profile.findUnique({ where: { id: "singleton" } });
  const name = profile?.name ?? "Portfolio";

  return {
    title: {
      template: `%s | ${name}`,
      default: `${name} | Portfolio`,
    },
  };
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const profile = await prisma.profile.findUnique({ where: { id: "singleton" } });

  return (
    <html lang="en">
      <body>
        <div className="min-h-screen px-4 py-6 sm:px-8">
          <Navbar photoUrl={profile?.photoSmallUrl} />
          <main className="mx-auto max-w-4xl px-0 pt-8 sm:px-4 lg:px-12">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
